### ISSUE TITLE
Polynomial RasterStack creation time

### ISSUE THREAD

**Issue by maxfreu** [rafaqz/Rasters.jl#226] opened 2021-11-18 13:44 UTC
Hi! It seems like the RasterStack creation time is polynomial wrt the number of input files. Is this to be expected? If yes, why? In my special case I'm loading Sentinel 2 data from one tile of a [force data cube](https://force-eo.readthedocs.io/en/latest/howto/datacube.html) using following code:

<details>
  <summary>Code</summary>

```julia
using Rasters
using Glob
using Dates
using Gnuplot

l2_folder = "/mnt/nas/projects/klimba/force/l2/europe/"
tile_folder = l2_folder * "X0031_Y0024/"
files = readdir(glob"*BOA.tif", tile_folder)
filenames = basename.(files)
times = [f[1:8] for f in filenames]
# times = DateTime.([f[1:8] for f in filenames], "yyyymmdd")

fs = filesize.(files)/10^9
##
nmax = 70
loading_times = Float64[]
for n in 1:2:nmax
    println(round(sum(fs[1:n])), " GB")
    t = @elapsed RasterStack(files[1:n], keys=Ti(Symbol.(times[1:n])));
    push!(loading_times, t)
end

##
begin
@gp "set title 'RasterStack creation time (Rasters v0.1.0)'"
@gp :- "set y2tics"
@gp :- "set key top left; set ytics nomirror"
@gp :- "set xl 'Number of files'"
@gp :- "set yl 'Load time [s]'"
@gp :- "set y2l 'Cumulative file size [GB]'"
@gp :- 1:2:nmax loading_times "w l t 'time'"
@gp :- 1:2:nmax [round(sum(fs[1:n])) for n in 1:2:nmax] "w l axes x1y2 t 'size'"
save(term="pngcairo size 640,480", output="~/RasterStackCreationTime.png")
end
```  
</details>

In a fresh session it looks like this:

![RasterStackCreationTime](https://user-images.githubusercontent.com/67329240/142423873-eca46508-d10f-4c8c-b5f3-f68ec377ccb2.png)

To avoid the x-y problem: What I'm actually trying to do is to lazily (spatial and temporal) index into a force data cube, which is essentially a bunch of tifs in folders. How would you tackle the problem? Probably using RasterStacks is going the wrong way? But maybe discourse is a better place for that question.

**Comment by rafaqz** [comment] 2021-11-18 17:07
Ok, there are a few issues to unpack here.

First, to fix something like this I really need the file causing the problem. Please include the code that downloads something I can use to reproduce this.

Second, for a time-series of files you probably want a `RasterSeries`? `RasterStack` is like a `NamedTuple` that can represent a multilayered Netcdf and similar things, but also act like a single array. POften named layers will be different kinds of data or number of dimensions, with the same extent. A time-series of near-identical objects is much better suited to a `RasterSeries`.

Third, I would guess what you're timing is mostly compilation time, that will scale like that due to object complexity. 

70 layers is a LOT for a stack, although 100 seconds is still far too long, and should be fixed. But you might find that a `RasterSeries` is much faster, as its a vector of same-typed objects, and should scale sub-linearly.

**Comment by maxfreu** [comment] 2021-11-20 13:39
Thanks for the reply. I also tried `RasterSeries` and it was indeed *much* faster. The reason why I tried the stack was that I liked the idea of being able to index into the stack with one call and getting back the data of all points in time at once. But broadcasting the getindex over the series or sth similar should also work fine.

1. I don't think this is related to any specific files; it's just about their number. If you want to, I could upload 20GB / ~45 files to my owncloud, which should be enough to see the effect. But it might be easier to just create a bunch of smaller rasters on your own and fill them with random data. I dont't think the effect depends on the raster size.
2. Covered at the beginning.
3. On the second try, it's much faster. It seems like as soon as the number of loaded files changes, a compilation is triggered. That's maybe the behavior to expect from a `NamedTuple`-like object. Loading 40 files for example takes 13s on the first try and 0.07s on the second. `@time` reports less than 1% compilation time on the first run, but I dont trust that number. Then loading 41 files takes 7s (why now less?). Initially I wanted to load 260 files and I have to do it just once at startup - but clearly `RasterStack`s are the wrong tool for that.

**Comment by rafaqz** [comment] 2021-11-21 00:06
1. Its just easier for me if I can run your script with no changes or organising files. That's what makes it a MWE. I have too many packages and too many things to add/fix in them, so anything like that helps.

3. It does seem to be compilation getting you there. `RasterStack` has a complicated type. But, there are also disk reads for the dimensions and metadata, so it is hard to know what the breakdown is. It is probably less load time for 41 files because half of the methods are compiled, and maybe some of the disk data is cached by your operating system. But I don't know really.

It would help a lot if you could investigate the first runs with ProfileView.jl and find where the time is being spent. I think there is some room to improve the compilation.

**Closed** 2024-03-24 20:58 UTC
Labels: performance
