### ISSUE TITLE
Rasters can not be read by QGIS

### ISSUE THREAD

**Issue by drsk0** [rafaqz/Rasters.jl#589] opened 2024-01-14 08:26 UTC
I think this is probably an issue on my side, but any help would be appreciated. When I open, and write a raster to disk, I can't open it any longer with QGIS.

```
write("test.tif", Raster("chirps-v2.0.2003.01.12.tif"))
```

Opening `test.tif` with QGIS fails with the message `test.tif is not a valid or recognized data source`.

QGIS: 3.34.2-Prizren
Rasters.jl:   [a3a2b9e3] v0.10.1

**Comment by rafaqz** [comment] 2024-01-14 09:32
You would have to share the file for me to know. 

GDAL is actually writing it underneath but we may do something strange with the metadata? Im not sure. I would have to actually check.

**Comment by drsk0** [comment] 2024-01-14 09:52
I'm testing with the rasters from the CHIRPS dataset. You can try with any raster found here: https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_daily/tifs/p05/2022/.

**Comment by felixcremer** [comment] 2024-01-15 15:25
I cannot reproduce this. I tried it with the first Raster in your link.
This is on Rasters 0.10.1 and   GDAL_jll v301.800.300+0
And on QGIS 3.22
This is on Ubuntut 22.04

This is my full manifest status:
<details><summary>Details</summary>
<p>


(@rastertest) pkg> st -m
Status `~/.julia/environments/rastertest/Manifest.toml`
  [621f4979] AbstractFFTs v1.5.0
  [79e6a3ab] Adapt v4.0.0
  [c9ce4bd3] ArchGDAL v0.10.2
  [4fba245c] ArrayInterface v7.7.0
⌅ [fa961155] CEnum v0.4.2
  [3da002f7] ColorTypes v0.11.4
  [c3611d14] ColorVectorSpace v0.10.0
  [5ae59095] Colors v0.12.10
  [187b0558] ConstructionBase v1.5.4
  [9a962f9c] DataAPI v1.15.0
  [e2d170a0] DataValueInterfaces v1.0.0
  [0703355e] DimensionalData v0.25.8
  [3c3547ce] DiskArrays v0.3.22
  [411431e0] Extents v0.1.2
  [bf96fef3] FieldMetadata v0.3.1
  [1a297f60] FillArrays v1.9.3
  [53c48c17] FixedPointNumbers v0.8.4
  [4c728ea3] Flatten v0.4.3
  [add2ef01] GDAL v1.7.0
  [68eda718] GeoFormatTypes v0.4.2
  [cf35fbd7] GeoInterface v1.3.3
  [0329782f] GeoInterfaceRecipes v1.0.2
  [a09fc81d] ImageCore v0.10.1
  [8197267c] IntervalSets v0.7.8
  [41ab1584] InvertedIndices v1.3.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.5.0
  [3da0fdf6] MPIPreferences v0.1.10
  [1914dd2f] MacroTools v0.5.13
  [dbb5928d] MappedArrays v0.4.2
  [e1d29d7a] Missings v1.1.0
  [e94cdb99] MosaicViews v0.3.4
  [6fe1bfb0] OffsetArrays v1.13.0
  [bac558e1] OrderedCollections v1.6.3
  [5432bcbf] PaddedViews v0.5.12
  [aea7be01] PrecompileTools v1.2.0
  [21216c6a] Preferences v1.4.1
  [92933f4c] ProgressMeter v1.9.0
  [a3a2b9e3] Rasters v0.10.1
  [3cdcf5f2] RecipesBase v1.3.4
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.0
  [efcf1570] Setfield v1.1.1
  [cae243ae] StackViews v0.1.1
  [1e83bf80] StaticArraysCore v1.4.2
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.11.1
  [62fd8b95] TensorCore v0.1.1
  [8ce61222] Arrow_jll v10.0.0+1
  [6e34b625] Bzip2_jll v1.0.8+1
  [2e619515] Expat_jll v2.5.0+0
  [a7073274] GDAL_jll v301.800.300+0
  [d604d12d] GEOS_jll v3.12.0+0
⌃ [0234f1f7] HDF5_jll v1.14.2+1
  [e33a78d0] Hwloc_jll v2.10.0+0
⌅ [a51ab1cf] ICU_jll v69.1.0+0
  [aacddb02] JpegTurbo_jll v3.0.1+0
  [b39eb1a6] Kerberos_krb5_jll v1.19.3+0
  [88015f11] LERC_jll v3.0.0+1
  [1d63c593] LLVMOpenMP_jll v15.0.7+0
  [dd4b983a] LZO_jll v2.10.1+0
  [08be9ffa] LibPQ_jll v16.0.0+0
  [94ce4f54] Libiconv_jll v1.17.0+0
⌅ [89763e89] Libtiff_jll v4.5.1+1
  [d3a379c0] LittleCMS_jll v2.15.0+0
  [5ced341a] Lz4_jll v1.9.4+0
  [7cb0a576] MPICH_jll v4.1.2+1
  [f1f71cc9] MPItrampoline_jll v5.3.1+1
  [9237b28f] MicrosoftMPI_jll v10.1.4+1
  [7243133f] NetCDF_jll v400.902.208+0
  [643b3616] OpenJpeg_jll v2.5.0+0
  [fe0851c0] OpenMPI_jll v5.0.1+0
  [458c3c95] OpenSSL_jll v3.0.12+0
  [32165bc3] PMIx_jll v4.2.7+0
  [58948b4f] PROJ_jll v901.300.0+0
  [76ed43ae] SQLite_jll v3.43.0+0
⌅ [e0b8ae26] Thrift_jll v0.16.0+0
  [02c8fc9c] XML2_jll v2.12.2+0
  [ffd25f8a] XZ_jll v5.4.5+0
  [3161d3a3] Zstd_jll v1.5.5+0
⌅ [28df3c45] boost_jll v1.76.0+1
  [477f73a3] libaec_jll v1.0.6+1
  [1080aeaf] libevent_jll v2.1.13+1
  [06c338fa] libgeotiff_jll v100.701.100+0
  [b53b4c65] libpng_jll v1.6.40+0
  [eb928a42] prrte_jll v3.0.2+0
  [fe1e1685] snappy_jll v1.1.9+1
  [0dad84c5] ArgTools v1.1.1
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [4af54fe1] LazyArtifacts
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.9.2
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [10745b16] Statistics v1.9.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.0.5+0
  [deac9b47] LibCURL_jll v8.4.0+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.2+0
  [14a3606d] MozillaCACerts_jll v2022.10.11
  [4536629a] OpenBLAS_jll v0.3.21+4
  [bea87d4a] SuiteSparse_jll v5.10.1+6
  [83775a58] Zlib_jll v1.2.13+0
  [8e850b90] libblastrampoline_jll v5.8.0+0
  [8e850ede] nghttp2_jll v1.52.0+1
  [3f19e933] p7zip_jll v17.4.0+0
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`

</p>
</details>

**Comment by drsk0** [comment] 2024-01-15 16:02
I tested it on a different computer and there it works as well, so it is a local problem. Here is my full manifest status:

<details>
```
(it4r) pkg> st -m
Status `~/it4r/Manifest.toml`
  [621f4979] AbstractFFTs v1.5.0
  [398f06c4] AbstractLattices v0.3.0
  [1520ce14] AbstractTrees v0.4.4
⌅ [79e6a3ab] Adapt v3.7.2
  [27a7e980] Animations v0.4.1
  [c9ce4bd3] ArchGDAL v0.10.2
  [dce04be8] ArgCheck v2.3.0
  [4fba245c] ArrayInterface v7.7.0
  [67c07d97] Automa v1.0.2
  [13072b0f] AxisAlgorithms v1.1.0
  [39de3d68] AxisArrays v0.4.7
  [198e06fe] BangBang v0.3.39
  [9718e550] Baselet v0.1.1
⌅ [fa961155] CEnum v0.4.2
  [96374032] CRlibm v1.0.1
  [00ebfdb7] CSTParser v3.4.0
  [159f3aea] Cairo v1.0.5
  [13f3f980] CairoMakie v0.11.5
  [49dc2e85] Calculus v0.5.1
⌃ [d360d2e6] ChainRulesCore v1.19.0
  [a2cac450] ColorBrewer v0.4.0
  [35d6a980] ColorSchemes v3.24.0
  [3da002f7] ColorTypes v0.11.4
  [c3611d14] ColorVectorSpace v0.10.0
  [5ae59095] Colors v0.12.10
  [861a8166] Combinatorics v1.0.2
  [a80b9123] CommonMark v0.8.12
  [bbf7d656] CommonSubexpressions v0.3.0
⌃ [34da2185] Compat v4.11.0
  [a33af91c] CompositionsBase v0.1.2
  [187b0558] ConstructionBase v1.5.4
  [d38c429a] Contour v0.6.2
  [150eb455] CoordinateTransformations v0.6.3
  [a8cc5b0e] Crayons v4.1.1
  [75c7ada1] DBFTables v1.2.4
  [9a962f9c] DataAPI v1.15.0
  [864edb3b] DataStructures v0.18.16
  [e2d170a0] DataValueInterfaces v1.0.0
  [244e2a9f] DefineSingletons v0.1.2
  [927a84f5] DelaunayTriangulation v0.8.11
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [0703355e] DimensionalData v0.25.8
  [3c3547ce] DiskArrays v0.3.22
  [31c24e10] Distributions v0.25.107
  [ffbed154] DocStringExtensions v0.9.3
  [fa6b7ba4] DualNumbers v0.6.8
  [4e289a0a] EnumX v1.0.4
  [429591f6] ExactPredicates v2.2.7
  [411431e0] Extents v0.1.2
  [7a1cc6ca] FFTW v1.7.2
  [bf96fef3] FieldMetadata v0.3.1
  [5789e2e9] FileIO v1.16.2
  [8fc22ac5] FilePaths v0.8.3
  [48062228] FilePathsBase v0.9.21
  [1a297f60] FillArrays v1.9.3
  [6a86dc24] FiniteDiff v2.22.0
  [53c48c17] FixedPointNumbers v0.8.4
  [4c728ea3] Flatten v0.4.3
  [59287772] Formatting v0.4.2
  [f6369f11] ForwardDiff v0.10.36
  [b38be410] FreeType v4.1.1
  [663a7486] FreeTypeAbstraction v0.10.1
  [add2ef01] GDAL v1.7.0
⌃ [46192b85] GPUArraysCore v0.1.5
  [92fee26a] GZip v0.6.2
  [2fb1d81b] GeoArrays v0.8.5
  [68eda718] GeoFormatTypes v0.4.2
  [cf35fbd7] GeoInterface v1.3.3
  [0329782f] GeoInterfaceRecipes v1.0.2
  [5c1252a2] GeometryBasics v0.4.9
  [c27321d9] Glob v1.3.1
  [a2bd30eb] Graphics v1.1.2
  [3955a311] GridLayoutBase v0.10.0
  [42e2da0e] Grisu v1.0.2
  [34004b35] HypergeometricFunctions v0.3.23
  [2803e5a7] ImageAxes v0.6.11
  [c817782e] ImageBase v0.1.7
  [a09fc81d] ImageCore v0.10.1
  [82e4d734] ImageIO v0.6.7
  [bc367c6b] ImageMetadata v0.9.9
  [9b13fd28] IndirectArrays v1.0.0
  [d25df0c9] Inflate v0.1.4
  [22cec73e] InitialValues v0.3.1
  [842dd82b] InlineStrings v1.4.0
  [18e54dd8] IntegerMathUtils v0.1.2
  [a98d9a8b] Interpolations v0.15.1
  [d1acc4aa] IntervalArithmetic v0.22.5
  [8197267c] IntervalSets v0.7.8
  [41ab1584] InvertedIndices v1.3.0
  [92d709cd] IrrationalConstants v0.2.2
  [f1662d9f] Isoband v0.1.1
  [c8e1da08] IterTools v1.10.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.5.0
  [682c06a0] JSON v0.21.4
  [b9b8584e] JSONRPC v1.3.6
  [b835a17e] JpegTurbo v0.1.5
  [98e50ef6] JuliaFormatter v1.0.45
  [5ab0869b] KernelDensity v0.6.8
  [b964fa9f] LaTeXStrings v1.3.1
  [2b0e0bc5] LanguageServer v4.5.0
  [8cdb02fc] LazyModules v0.3.1
  [9c8b4983] LightXML v0.9.1
  [d3d80556] LineSearches v7.2.0
  [9b3f67b0] LinearAlgebraX v0.2.6
  [2ab3a3ac] LogExpFunctions v0.3.26
  [3da0fdf6] MPIPreferences v0.1.10
  [1914dd2f] MacroTools v0.5.12
  [ee78f7c6] Makie v0.20.4
  [20f20a25] MakieCore v0.7.2
  [dbb5928d] MappedArrays v0.4.2
  [0a4f8689] MathTeXEngine v0.5.7
  [128add7d] MicroCollections v0.1.4
  [e1d29d7a] Missings v1.1.0
  [7475f97c] Mods v2.2.3
  [e94cdb99] MosaicViews v0.3.4
  [3b2b4ff1] Multisets v0.4.4
  [d41bc354] NLSolversBase v7.8.3
  [77ba4419] NaNMath v1.0.2
  [f09324ee] Netpbm v1.1.1
  [510215fc] Observables v0.5.5
  [6fe1bfb0] OffsetArrays v1.13.0
  [52e1d378] OpenEXR v0.3.2
  [429524aa] Optim v1.7.8
  [bac558e1] OrderedCollections v1.6.3
  [90014a1f] PDMats v0.11.31
  [f57f5aa1] PNGFiles v0.4.3
  [19eb6ba3] Packing v0.5.0
  [5432bcbf] PaddedViews v0.5.12
  [d96e819e] Parameters v0.12.3
  [69de0a69] Parsers v2.8.1
  [2ae35dd2] Permutations v0.4.19
  [eebad327] PkgVersion v0.3.3
  [995b91a9] PlotUtils v1.4.0
  [647866c9] PolygonOps v0.1.2
  [f27b6e38] Polynomials v4.0.6
  [85a6dd25] PositiveFactorizations v0.2.4
  [aea7be01] PrecompileTools v1.2.0
  [21216c6a] Preferences v1.4.1
  [27ebfcd6] Primes v0.5.5
  [92933f4c] ProgressMeter v1.9.0
  [4b34888f] QOI v1.0.0
⌃ [1fd47b50] QuadGK v2.9.1
  [b3c3ace0] RangeArrays v0.3.2
  [a3a2b9e3] Rasters v0.10.1
  [c84ed2f1] Ratios v0.4.5
  [3cdcf5f2] RecipesBase v1.3.4
  [189a3867] Reexport v1.2.2
  [05181044] RelocatableFolders v1.0.1
  [ae029012] Requires v1.3.0
  [286e9d63] RingLists v0.2.8
  [79098fc4] Rmath v0.7.1
  [5eaf0fd0] RoundingEmulator v0.2.1
  [6c6a2e73] Scratch v1.2.1
  [efcf1570] Setfield v1.1.1
  [65257c39] ShaderAbstractions v0.4.0
⌃ [8e980c4a] Shapefile v0.11.0
  [992d4aef] Showoff v1.0.3
  [73760f76] SignedDistanceFields v0.4.0
  [55797a34] SimpleGraphs v0.8.6
  [ec83eff0] SimplePartitions v0.3.1
  [cc47b68c] SimplePolynomials v0.2.17
  [a6525b86] SimpleRandom v0.3.1
  [699a6c99] SimpleTraits v0.9.4
  [45858cf5] Sixel v0.1.3
  [a2af1166] SortingAlgorithms v1.2.1
  [276daf66] SpecialFunctions v2.3.1
  [171d559e] SplittablesBase v0.1.15
  [c5dd0088] StableHashTraits v1.1.4
  [cae243ae] StackViews v0.1.1
⌃ [90137ffa] StaticArrays v1.9.0
  [1e83bf80] StaticArraysCore v1.4.2
  [b3cc710f] StaticLint v8.2.0
  [82ae8749] StatsAPI v1.7.0
  [2913bbd2] StatsBase v0.34.2
  [4c63d2b9] StatsFuns v1.3.0
  [09ab397b] StructArrays v0.6.16
  [cf896787] SymbolServer v7.3.0
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.11.1
  [62fd8b95] TensorCore v0.1.1
  [76b0de8b] TestItemDetection v0.2.0
⌅ [731e570b] TiffImages v0.6.8
  [0796e94c] Tokenize v0.5.28
  [3bb67fe8] TranscodingStreams v0.10.2
  [28d57a85] Transducers v0.4.80
  [981d1d27] TriplotBase v0.1.0
  [9d95972d] TupleTools v1.4.3
  [5c2747f8] URIs v1.5.1
  [3a884ed6] UnPack v1.0.2
  [1cfade01] UnicodeFun v0.4.1
  [ea10d353] WeakRefStrings v1.4.2
  [efce3f68] WoodburyMatrices v1.0.0
  [8ce61222] Arrow_jll v10.0.0+1
  [6e34b625] Bzip2_jll v1.0.8+0
  [4e9b3aee] CRlibm_jll v1.0.1+0
  [83423d85] Cairo_jll v1.16.1+1
  [5ae413db] EarCut_jll v2.2.4+0
  [2e619515] Expat_jll v2.5.0+0
  [b22a6f82] FFMPEG_jll v4.4.4+1
  [f5851436] FFTW_jll v3.3.10+0
  [a3f928ae] Fontconfig_jll v2.13.93+0
  [d7e528f0] FreeType2_jll v2.13.1+0
  [559328eb] FriBidi_jll v1.0.10+0
  [a7073274] GDAL_jll v301.800.300+0
  [d604d12d] GEOS_jll v3.12.0+0
  [78b55507] Gettext_jll v0.21.0+0
  [7746bdde] Glib_jll v2.76.5+0
  [3b182d85] Graphite2_jll v1.3.14+0
⌃ [0234f1f7] HDF5_jll v1.14.2+1
  [2e76f6c2] HarfBuzz_jll v2.8.1+1
  [e33a78d0] Hwloc_jll v2.10.0+0
⌅ [a51ab1cf] ICU_jll v69.1.0+0
  [905a6f67] Imath_jll v3.1.7+0
  [1d5cc7b8] IntelOpenMP_jll v2024.0.2+0
  [aacddb02] JpegTurbo_jll v3.0.1+0
  [b39eb1a6] Kerberos_krb5_jll v1.19.3+0
  [c1c5ebd0] LAME_jll v3.100.1+0
  [88015f11] LERC_jll v3.0.0+1
  [1d63c593] LLVMOpenMP_jll v15.0.7+0
  [dd4b983a] LZO_jll v2.10.1+0
  [08be9ffa] LibPQ_jll v16.0.0+0
⌅ [e9f186c6] Libffi_jll v3.2.2+1
  [d4300ac3] Libgcrypt_jll v1.8.7+0
  [7add5ba3] Libgpg_error_jll v1.42.0+0
  [94ce4f54] Libiconv_jll v1.17.0+0
  [4b2f31a3] Libmount_jll v2.35.0+0
⌅ [89763e89] Libtiff_jll v4.5.1+1
  [38a345b3] Libuuid_jll v2.36.0+0
  [d3a379c0] LittleCMS_jll v2.15.0+0
  [5ced341a] Lz4_jll v1.9.4+0
  [856f044c] MKL_jll v2024.0.0+0
  [7cb0a576] MPICH_jll v4.1.2+1
  [f1f71cc9] MPItrampoline_jll v5.3.1+1
  [9237b28f] MicrosoftMPI_jll v10.1.4+1
  [7243133f] NetCDF_jll v400.902.208+0
  [e7412a2a] Ogg_jll v1.3.5+1
  [18a262bb] OpenEXR_jll v3.1.4+0
  [643b3616] OpenJpeg_jll v2.5.0+0
  [fe0851c0] OpenMPI_jll v5.0.1+0
  [458c3c95] OpenSSL_jll v3.0.12+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [91d4177d] Opus_jll v1.3.2+0
  [32165bc3] PMIx_jll v4.2.7+0
  [58948b4f] PROJ_jll v901.300.0+0
  [36c8627f] Pango_jll v1.50.14+0
  [30392449] Pixman_jll v0.42.2+0
  [f50d1b31] Rmath_jll v0.4.0+0
  [76ed43ae] SQLite_jll v3.43.0+0
⌅ [e0b8ae26] Thrift_jll v0.16.0+0
  [02c8fc9c] XML2_jll v2.12.2+0
  [aed1982a] XSLT_jll v1.1.34+0
  [ffd25f8a] XZ_jll v5.4.5+0
  [4f6342f7] Xorg_libX11_jll v1.8.6+0
  [0c0b7dd1] Xorg_libXau_jll v1.0.11+0
  [a3789734] Xorg_libXdmcp_jll v1.1.4+0
  [1082639a] Xorg_libXext_jll v1.3.4+4
  [ea2f1a96] Xorg_libXrender_jll v0.9.10+4
  [14d82f49] Xorg_libpthread_stubs_jll v0.1.1+0
  [c7cfdc94] Xorg_libxcb_jll v1.15.0+0
  [c5fb5394] Xorg_xtrans_jll v1.5.0+0
  [3161d3a3] Zstd_jll v1.5.5+0
⌅ [28df3c45] boost_jll v1.76.0+1
  [9a68df92] isoband_jll v0.2.3+0
  [477f73a3] libaec_jll v1.0.6+1
  [a4ae2306] libaom_jll v3.4.0+0
  [0ac62f75] libass_jll v0.15.1+0
  [1080aeaf] libevent_jll v2.1.13+1
  [f638f0a6] libfdk_aac_jll v2.0.2+0
  [06c338fa] libgeotiff_jll v100.701.100+0
  [b53b4c65] libpng_jll v1.6.40+0
  [075b6546] libsixel_jll v1.10.3+0
  [f27f6e37] libvorbis_jll v1.3.7+1
  [eb928a42] prrte_jll v3.0.2+0
  [fe1e1685] snappy_jll v1.1.9+1
  [1270edf5] x264_jll v2021.5.5+0
  [dfaa095f] x265_jll v3.5.0+0
  [0dad84c5] ArgTools v1.1.1
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [8bf52ea8] CRC32c
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [4af54fe1] LazyArtifacts
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.9.2
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [10745b16] Statistics v1.9.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.0.5+0
  [deac9b47] LibCURL_jll v8.4.0+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.2+0
  [14a3606d] MozillaCACerts_jll v2022.10.11
  [4536629a] OpenBLAS_jll v0.3.21+4
  [05823500] OpenLibm_jll v0.8.1+0
  [efcefdf7] PCRE2_jll v10.42.0+0
  [bea87d4a] SuiteSparse_jll v5.10.1+6
  [83775a58] Zlib_jll v1.2.13+0
  [8e850b90] libblastrampoline_jll v5.8.0+0
  [8e850ede] nghttp2_jll v1.52.0+1
  [3f19e933] p7zip_jll v17.4.0+0
I
```
</details>

**Comment by rafaqz** [comment] 2024-01-15 19:45
We cant actually see GDAL_jll in that list, maybe check you manifest file. 

But it looks like its the same GDAL.jl and Rasters.jl. 

Whats your qgis version?

**Comment by felixcremer** [comment] 2024-01-15 20:03
The GDAL_jll version is the same for both of us. 

What is the output of `Raster("chirps-v2.0.2003.01.12.tif")` ?
I am wondering whether Rasters is permuting the dimensions somehow and QGIS is not able to open it then because I had that case once with NetCDF files.
Can you open the test.tif file with Rasters again?
Can you open the test.tif file on the QGIS on your other computer?

**Comment by rafaqz** [comment] 2024-02-01 23:24
Closing, seems like a qgis version issue to me

**Closed by rafaqz** 2024-02-01 23:24 UTC
