### ISSUE TITLE
Makie incompatibility

### ISSUE THREAD

**Issue by mrke** [rafaqz/Rasters.jl#571] opened 2023-12-05 12:58 UTC
this code from the examples produces the error pasted below it:

using Rasters,
      NCDatasets,
      RasterDataSources,
      ArchGDAL,
      Dates
using CairoMakie
ENV["RASTERDATASOURCES_PATH"] = "c:/Spatial_Data/Data/"
A = Raster(WorldClim{BioClim}, 5)
madagascar = view(A, X(43.25 .. 50.48), Y(-25.61 .. -12.04))
Makie.plot(madagascar)

Error:

ERROR: MethodError: Cannot `convert` an object of type 
  DimArray{ColorTypes.RGBA{Float32}, 2, Tuple{X{Projected{Float64, LinRange{Float64, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Float64}, DimensionalData.Dimensions.LookupArrays.Intervals{DimensionalData.Dimensions.LookupArrays.Start}, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}, WellKnownText{GeoFormatTypes.CRS}, Nothing, X{Colon}}}, Y{Projected{Float64, LinRange{Float64, Int64}, DimensionalData.Dimensions.LookupArrays.ReverseOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Float64}, DimensionalData.Dimensions.LookupArrays.Intervals{DimensionalData.Dimensions.LookupArrays.Start}, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}, WellKnownText{GeoFormatTypes.CRS}, Nothing, Y{Colon}}}}, Tuple{Rasters.Band{DimensionalData.Dimensions.LookupArrays.Categorical{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, Matrix{ColorTypes.RGBA{Float32}}, Symbol, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}} to an object of type 
  Union{ColorTypes.RGBA{Float32}, Matrix{ColorTypes.RGBA{Float32}}}
Closest candidates are:
  convert(::Type{T}, ::T) where T at Base.jl:61
Stacktrace:
  [1] numbers_to_colors(numbers::DimArray{Float32, 2, Tuple{X{Projected{Float64, LinRange{Float64, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Float64}, DimensionalData.Dimensions.LookupArrays.Intervals{DimensionalData.Dimensions.LookupArrays.Start}, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}, WellKnownText{GeoFormatTypes.CRS}, Nothing, X{Colon}}}, Y{Projected{Float64, LinRange{Float64, Int64}, DimensionalData.Dimensions.LookupArrays.ReverseOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Float64}, DimensionalData.Dimensions.LookupArrays.Intervals{DimensionalData.Dimensions.LookupArrays.Start}, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}, WellKnownText{GeoFormatTypes.CRS}, Nothing, Y{Colon}}}}, Tuple{Rasters.Band{DimensionalData.Dimensions.LookupArrays.Categorical{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, Matrix{Float32}, Symbol, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}}, colormap::Vector{ColorTypes.RGBA{Float32}}, colorscale::Function, colorrange::Vec{2, Float32}, lowclip::ColorTypes.RGBA{Float32}, highclip::ColorTypes.RGBA{Float32}, nan_color::ColorTypes.RGBA{Float32})
    @ Makie C:\Users\mrke\.julia\packages\Makie\RgxaV\src\colorsampler.jl:163
  [2] to_color(c::Makie.ColorMapping{2, DimArray{Float32, 2, Tuple{X{Projected{Float64, LinRange{Float64, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Float64}, DimensionalData.Dimensions.LookupArrays.Intervals{DimensionalData.Dimensions.LookupArrays.Start}, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}, WellKnownText{GeoFormatTypes.CRS}, Nothing, X{Colon}}}, Y{Projected{Float64, LinRange{Float64, Int64}, DimensionalData.Dimensions.LookupArrays.ReverseOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Float64}, DimensionalData.Dimensions.LookupArrays.Intervals{DimensionalData.Dimensions.LookupArrays.Start}, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}, WellKnownText{GeoFormatTypes.CRS}, Nothing, Y{Colon}}}}, Tuple{Rasters.Band{DimensionalData.Dimensions.LookupArrays.Categorical{Int64, UnitRange{Int64}, 
DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, Matrix{Float32}, Symbol, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}}, DimArray{Float32, 2, Tuple{X{Projected{Float64, LinRange{Float64, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Float64}, DimensionalData.Dimensions.LookupArrays.Intervals{DimensionalData.Dimensions.LookupArrays.Start}, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}, WellKnownText{GeoFormatTypes.CRS}, Nothing, X{Colon}}}, Y{Projected{Float64, LinRange{Float64, Int64}, DimensionalData.Dimensions.LookupArrays.ReverseOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Float64}, DimensionalData.Dimensions.LookupArrays.Intervals{DimensionalData.Dimensions.LookupArrays.Start}, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}, WellKnownText{GeoFormatTypes.CRS}, Nothing, Y{Colon}}}}, Tuple{Rasters.Band{DimensionalData.Dimensions.LookupArrays.Categorical{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, Matrix{Float32}, Symbol, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}}})
    @ Makie C:\Users\mrke\.julia\packages\Makie\RgxaV\src\colorsampler.jl:322
  [3] draw_atomic(scene::Scene, screen::CairoMakie.Screen{CairoMakie.IMAGE}, primitive::Union{Heatmap, Image})
    @ CairoMakie C:\Users\mrke\.julia\packages\CairoMakie\VqiwS\src\primitives.jl:718
  [4] draw_plot(scene::Scene, screen::CairoMakie.Screen{CairoMakie.IMAGE}, primitive::Heatmap{Tuple{Vector{Float32}, Vector{Float32}, DimArray{Float32, 2, Tuple{X{Projected{Float64, LinRange{Float64, Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Float64}, DimensionalData.Dimensions.LookupArrays.Intervals{DimensionalData.Dimensions.LookupArrays.Start}, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}, WellKnownText{GeoFormatTypes.CRS}, Nothing, X{Colon}}}, Y{Projected{Float64, LinRange{Float64, Int64}, DimensionalData.Dimensions.LookupArrays.ReverseOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Float64}, DimensionalData.Dimensions.LookupArrays.Intervals{DimensionalData.Dimensions.LookupArrays.Start}, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}, WellKnownText{GeoFormatTypes.CRS}, Nothing, Y{Colon}}}}, Tuple{Rasters.Band{DimensionalData.Dimensions.LookupArrays.Categorical{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, Matrix{Float32}, Symbol, DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.GDALsource, Dict{String, Any}}}}})   
    @ CairoMakie C:\Users\mrke\.julia\packages\CairoMakie\VqiwS\src\infrastructure.jl:131
  [5] cairo_draw(screen::CairoMakie.Screen{CairoMakie.IMAGE}, scene::Scene)
    @ CairoMakie C:\Users\mrke\.julia\packages\CairoMakie\VqiwS\src\infrastructure.jl:51
  [6] backend_show(screen::CairoMakie.Screen{CairoMakie.IMAGE}, io::Base64.Base64EncodePipe, #unused#::MIME{Symbol("image/png")}, scene::Scene)
    @ CairoMakie C:\Users\mrke\.julia\packages\CairoMakie\VqiwS\src\display.jl:111
  [7] show(io::Base64.Base64EncodePipe, m::MIME{Symbol("image/png")}, figlike::Makie.FigureAxisPlot)        
    @ Makie C:\Users\mrke\.julia\packages\Makie\RgxaV\src\display.jl:248
  [8] base64encode(::Function, ::MIME{Symbol("image/png")}, ::Vararg{Any}; context::Nothing)
    @ Base64 C:\Users\mrke\AppData\Local\Programs\Julia-1.8.5\share\julia\stdlib\v1.8\Base64\src\encode.jl:209
  [9] _binstringmime
    @ C:\Users\mrke\AppData\Local\Programs\Julia-1.8.5\share\julia\stdlib\v1.8\Base64\src\Base64.jl:46 [inlined]
 [10] #stringmime#8
    @ C:\Users\mrke\AppData\Local\Programs\Julia-1.8.5\share\julia\stdlib\v1.8\Base64\src\Base64.jl:43 [inlined]
 [11] stringmime
    @ C:\Users\mrke\AppData\Local\Programs\Julia-1.8.5\share\julia\stdlib\v1.8\Base64\src\Base64.jl:43 [inlined]
 [12] display(d::VSCodeServer.InlineDisplay, m::MIME{Symbol("image/png")}, x::Makie.FigureAxisPlot)
    @ VSCodeServer c:\Users\mrke\.vscode\extensions\julialang.language-julia-1.60.2\scripts\packages\VSCodeServer\src\display.jl:68
 [13] display(d::VSCodeServer.InlineDisplay, mime::String, x::Any)
    @ Base.Multimedia .\multimedia.jl:216
 [14] display(d::VSCodeServer.InlineDisplay, x::Makie.FigureAxisPlot)
    @ VSCodeServer c:\Users\mrke\.vscode\extensions\julialang.language-julia-1.60.2\scripts\packages\VSCodeServer\src\display.jl:204
 [15] display(x::Any)
    @ Base.Multimedia .\multimedia.jl:328
 [16] display(figlike::Makie.FigureAxisPlot; backend::Module, inline::MakieCore.Automatic, update::Bool, screen_config::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie C:\Users\mrke\.julia\packages\Makie\RgxaV\src\display.jl:145
 [17] display(figlike::Makie.FigureAxisPlot)
    @ Makie C:\Users\mrke\.julia\packages\Makie\RgxaV\src\display.jl:131
 [18] #invokelatest#2
    @ .\essentials.jl:729 [inlined]
 [19] invokelatest
    @ .\essentials.jl:726 [inlined]
 [20] (::VSCodeServer.var"#67#72"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\mrke\.vscode\extensions\julialang.language-julia-1.60.2\scripts\packages\VSCodeServer\src\eval.jl:229
 [21] withpath(f::VSCodeServer.var"#67#72"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams}, path::String)
    @ VSCodeServer c:\Users\mrke\.vscode\extensions\julialang.language-julia-1.60.2\scripts\packages\VSCodeServer\src\repl.jl:274
 [22] (::VSCodeServer.var"#66#71"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\mrke\.vscode\extensions\julialang.language-julia-1.60.2\scripts\packages\VSCodeServer\src\eval.jl:179
 [23] hideprompt(f::VSCodeServer.var"#66#71"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})
    @ VSCodeServer c:\Users\mrke\.vscode\extensions\julialang.language-julia-1.60.2\scripts\packages\VSCodeServer\src\repl.jl:38
 [24] (::VSCodeServer.var"#65#70"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\mrke\.vscode\extensions\julialang.language-julia-1.60.2\scripts\packages\VSCodeServer\src\eval.jl:150
 [25] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging .\logging.jl:511
 [26] with_logger
    @ .\logging.jl:623 [inlined]
 [27] (::VSCodeServer.var"#64#69"{VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\mrke\.vscode\extensions\julialang.language-julia-1.60.2\scripts\packages\VSCodeServer\src\eval.jl:255
 [28] #invokelatest#2
    @ .\essentials.jl:729 [inlined]
 [29] invokelatest(::Any)
    @ Base .\essentials.jl:726
 [30] macro expansion
    @ c:\Users\mrke\.vscode\extensions\julialang.language-julia-1.60.2\scripts\packages\VSCodeServer\src\eval.jl:34 [inlined]
 [31] (::VSCodeServer.var"#62#63")()
    @ VSCodeServer .\task.jl:484

**Comment by rafaqz** [comment] 2023-12-06 18:57
I still haven't been able to reproduce this sorry

**Comment by felixcremer** [comment] 2023-12-08 16:00
I also can't reproduce it. Are you on julia 1.8.5? Maybe it would be resolved by updating to the newest Julia version. Also what is the output of Pkg.status()?
I can't test it on Julia 1.8.5 , because I ran into compatibility problems with my environment.

**Comment by asinghvi17** [comment] 2024-09-10 23:30
I can't reprodce this, should we close as stale?

**Closed** 2024-09-11 10:21 UTC
